import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

try:
 
    df = pd.read_csv(r"C:\Users\indur\OneDrive\Desktop\depolyment projects\zomato_project\zomato_clean_data_set.csv")
    print("‚úÖ CSV file loaded successfully")


    user = 'root'
    password = quote_plus('induri@05')  
    host = 'localhost'
    database = 'zomato_db'

   
    engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}/{database}')

    df.to_sql('zomato_clean_data_set', con=engine, if_exists='replace', index=False)
    print("‚úÖ Data successfully loaded into MySQL table: zomato_clean_data_set")

except Exception as e:
    print("‚ùå Error while loading data:", e)

finally:
    print("üëç ETL process completed.")
